# Generated by Django 2.2.6 on 2019-10-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MomoRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(max_length=12)),
                ('amount', models.CharField(max_length=250)),
                ('external_id', models.CharField(max_length=250)),
                ('payee_note', models.TextField()),
                ('payee_message', models.TextField()),
                ('currency', models.CharField(max_length=25)),
                ('transaction_ref', models.TextField()),
                ('request_status', models.CharField(max_length=250)),
                ('lastest_api_response', models.TextField()),
            ],
        ),
    ]
