# Generated by Django 2.2.6 on 2019-10-16 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momorequest',
            old_name='transaction_ref',
            new_name='reference',
        ),
    ]
