# Generated by Django 2.2.6 on 2019-10-16 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('momo_app', '0002_auto_20191016_1007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='momorequest',
            old_name='lastest_api_response',
            new_name='new_momo_response',
        ),
    ]
